### ISSUE TITLE
Add feature to sort highlights by page location, instead of timestamp

### ISSUE THREAD

**Issue by thomasvs** [jsonMartin/readwise-mirror#10]
Here's a snippet with 4 extracted notes:

---

Both the Judge’s view and the Sage’s view are self-fulfilling prophecies. Each of us is a mixed bag, both divine and wretched. Whether you are in Sage or Saboteur mode determines which version of you gets manifested. ([798](https://readwise.io/to_kindle?action=open&asin=B007R0IQ70&location=798)) %% Color: yellow %% ^204391114

---

The second way the Judge sabotages us is by judging others. The Judge plays a central role in team, professional, and personal conflicts. ([802](https://readwise.io/to_kindle?action=open&asin=B007R0IQ70&location=802)) %% Color: yellow %% ^204391115

---

With Positive Intelligence you can both measure and significantly improve the percentage of time that your mind is serving you rather than sabotaging you. ([117](https://readwise.io/to_kindle?action=open&asin=B007R0IQ70&location=117)) %% Color: yellow %% ^204881490

---

Using the principles of Positive Intelligence, we devised a core question to reframe and redirect the team’s perspective and redirect its efforts: “What do we need to do so that within three years we can say this current crisis was the best thing that could have happened to our company?” ([139](https://readwise.io/to_kindle?action=open&asin=B007R0IQ70&location=139)) %% Color: yellow %% ^204881491

Note that the location on the last two is before the location on the first two.

In this particular case, I think that it's sorting by the timestamp of when I highlighted, not of where they appear in the book.

**Comment by jsonMartin** [comment]
Hey @thomasvs , so as you guessed, the highlights are already sorted by timestamp when the plugin retrieves them via Readwise's API, this is how the data is presented by default.

I added an option to reverse the sort order from newest to oldest; however, highlights will still not be ordered by page number which is what I think it looks like you're looking for here.

I think that sorting highlights by page location would be a good feature so I'll add that to the roadmap 👍
