### ISSUE TITLE
How does this compare to the readwise official now that it is out?

### ISSUE THREAD

**Issue by tonyxiao** [jsonMartin/readwise-mirror#16]

**Comment by jsonMartin** [comment]
The main difference between Readwise Official and Readwise Mirror is **one-way sync**. 

Readwise Mirror uses the Readwise API as the source of truth, so all updates will be mirrored within Obsidian library, ensuring data is always in sync. This allows edits to existing highlights to update properly, such as adding notes or changing highlight color. 

The Readwise Official plugin (as well as other community plugins) works in an append mode, meaning that new highlights are added to the end of the existing note. If you plan on customizing your notes inside Obsidian, then you'd want to go this route; but a downside of this method is that edits to existing highlights aren't synced (which is the main reason I initially developed this plugin). 

> From [Readwise's Obsidian Plugin FAQ](https://help.readwise.io/article/125-how-does-the-readwise-to-obsidian-export-integration-work)
> What happens when I update highlights in Readwise? Will those changes automatically sync with Obsidian? (Or vice versa?)
>
> At the moment, no. Because Obsidian uses a page is its atomic unit, it would be quite technically challenging to programmatically search through an existing page for the right highlight and update that text without accidentally overwriting edits by the user. 

See this section in the Readme: https://github.com/jsonMartin/readwise-mirror#one-way-mirror-sync-vs-append-based-sync
