### ISSUE TITLE
Modification request

### ISSUE THREAD

**Issue by Irshaadv** [jsonMartin/readwise-mirror#23]
Hi Jason, 

Wondering if you would be open to making some paid changes to this plugin? Specifically, want to make each highlight it's own note etc. 

Best, 
Irshaad

**Comment by jsonMartin** [comment]
Hey @Irshaadv ! Just saw your message, the last couple of weeks have been busy. 

Sure, I'd be happy to discuss your change requests. Please shoot me an e-mail at [dev@jasonmart.in](mailto:dev@jasonmart.in) and we can discuss the details 👍

**Comment by jsonMartin** [comment]
Hi @Irshaadv, since I haven't heard back I've gone ahead and closed this. 

Feel free to contact me if you have any questions or would like to discuss this further.

Thanks
