### ISSUE TITLE
Partial note sections

### ISSUE THREAD

**Issue by martinandrovich** [jsonMartin/readwise-mirror#24]
Would it be possible to have a note with "partial sections"? For example, the plugin would update everything except a list of specified sections, as:

```
---
id: {{ id }}
updated: {{ updated }}
title: {{ title }}
author: {{ author }}
---

# Summary
This section would not be updated by the plugin.

# Key Insights
This section would not be updated by the plugin.

# Highlights
```

**Comment by jsonMartin** [comment]
Hi @martinandrovich, unfortunately this is not currently on the roadmap, but I'd be happy to welcome a PR adding the feature.

**Comment by martinandrovich** [comment]
@jsonMartin Fair enough! I think a more generic solution (or just an alternative) would maybe be to have a file per highlight within a folder for a given article/book/etc - I think there was an opened issue with a similar suggestion.
