### ISSUE TITLE
Feature Request: Include Document Tags

### ISSUE THREAD

**Issue by FTWynn** [jsonMartin/readwise-mirror#3]
First,  I love the concept of this plugin. I think treating Readwise as the authoritative source is the right answer to keep everything sanely managed.

I do have a feature request: to add document tags to the generated files. Particularly if I can't/shouldn't add tags to the generated files, then pulling in the tags from Readwise seems like the next best thing. I know at least for my use case, there's no need to drill into individual highlight tags, but the book ones could be useful inside the About section.

**Comment by jsonMartin** [comment]
Hey @FTWynn , thanks and glad you're loving the plugin.

Tag support is a great idea. And what a coincidence, this GitHub issue is timely - I just spoke to one of their developers this morning over e-mail, and they told me: 
>In the next couple days we’re gonna ship support for highlight and book tags in the public API, just fyi ;) 

So after this change is finalized in their public API, I'll work on integrating this feature 👍

**Comment by jsonMartin** [comment]
Hi @FTWynn , tag support has just been added in release version 1.1.0: https://github.com/jsonMartin/readwise-mirror/releases/tag/1.1.0

It should be available to update now within Obsidian. Hope this helps, and let me know if you run into any issues with tags
