### ISSUE TITLE
Are these comments needed for the plugin to operate correctly?

### ISSUE THREAD

**Issue by joefrancia** [jsonMartin/readwise-mirror#35]
I just started with this plugin, which I like quite a bit better than the official one. I noticed there are comments in the default template, like so:

```
%%
ID: 33167075
Updated: 2023-10-15
%%
```

Are these needed for the proper functioning of the plugin, or can they be removed from the template?

**Comment by jsonMartin** [comment]
Hi @joefrancia , glad you like the Readwise Mirror plugin.

This should be safe to remove from the template, it's just [Obsidian's comment syntax](https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#Comments) which should only show up in the editor mode.
