### ISSUE TITLE
Bug: Title links don't always link to the note itself

### ISSUE THREAD

**Issue by FTWynn** [jsonMartin/readwise-mirror#4]
I've noticed that Titles with filename-illegal characters are kept in the note, making the `Title` self-link broken.

Perhaps they should reflect the resultant filename instead?

![image](https://user-images.githubusercontent.com/81338/119720451-d4989d80-be1e-11eb-8b8e-a393d3a01d65.png)

**Comment by jsonMartin** [comment]
@FTWynn Good find, thanks for pointing this bug out!

I'll fix this in the next upcoming patch; after it's installed and you regenerate your notes, these broken links should automatically be fixed 👍😊

**Comment by jsonMartin** [comment]
Hey @FTWynn , this should be fixed now in version 1.0.2: https://github.com/jsonMartin/readwise-mirror/releases/tag/1.0.2

Let me know if you still run into issues after the new version 👍
