### ISSUE TITLE
"Author::" instead of "Author:"

### ISSUE THREAD

**Issue by Sab73** [jsonMartin/readwise-mirror#5]
Hi, 

great plugin there, thank you!

I have only one minor problem using it: I cannot query meta data fields (in the #About section) with the Dataview plugin in Obsidian, since you do not use the double colon format after the meta data field names (only a single colon). 

Any chance to update/modify this or provide an option for using meta data field names with that syntax (or to provide an option to use a custom import template file)?

Thank you and keep up the good work, your plugin rocks.

Cheers,

Szabolcs

**Comment by jsonMartin** [comment]
> Hi, 
> 
> great plugin there, thank you!
> 
> I have only one minor problem using it: I cannot query meta data fields (in the #About section) with the Dataview plugin in Obsidian, since you do not use the double colon format after the meta data field names (only a single colon). 
> 
> Any chance to update/modify this or provide an option for using meta data field names with that syntax (or to provide an option to use a custom import template file)?
> 
> Thank you and keep up the good work, your plugin rocks.
> 
> Cheers,
> 
> Szabolcs

Hey @Sab73 , that's a good suggestion. I do actually have custom templates on the feature roadmap, so that would probably be the best solution to this issue.

I am planning on adding support for tags first for next release, then will look into custom templating for the upcoming release after.

**Comment by Sab73** [comment]
> > Hi,
> > great plugin there, thank you!
> > I have only one minor problem using it: I cannot query meta data fields (in the #About section) with the Dataview plugin in Obsidian, since you do not use the double colon format after the meta data field names (only a single colon).
> > Any chance to update/modify this or provide an option for using meta data field names with that syntax (or to provide an option to use a custom import template file)?
> > Thank you and keep up the good work, your plugin rocks.
> > Cheers,
> > Szabolcs
> 
> Hey @Sab73 , that's a good suggestion. I do actually have custom templates on the feature roadmap, so that would probably be the best solution to this issue.
> 
> I am planning on adding support for tags first for next release, then will look into custom templating for the upcoming release after.

Sound great! Thank you.

**Comment by jsonMartin** [comment]
Hi @Sab73 , just to update you on this the Templating engine has been added to this plugin as of newest version 1.2.0, so this should help address your issue =)
