### ISSUE TITLE
Feature request: SyncLog as md.file

### ISSUE THREAD

**Issue by thtack** [jsonMartin/readwise-mirror#6]
Thank you for this powerful and helpful tool, which enables a workflow I missed from my late Notion system. 
I just wondered if adding a md SyncLog into the SyncFolder might help to get better information about articles or books that have been updated recently.
With some 100+-Kindle-books it is cumbersome to remember which books I have dealt with lately.
Thank you for considering my suggestion.

**Comment by jsonMartin** [comment]
Hi @thtack , thanks for the suggestion. 

Information for the current sync session can actually be found inside the debug console inside Obsidian. However, that information doesn't persist and there is currently no way to see past sync logs.

I will consider extending the logging module in a future update to allow an option to write these notifications to log file in the Readwise Library folder

**Comment by jsonMartin** [comment]
Hey @thtack , I implemented this functionality in the newest Release v1.1.1: https://github.com/jsonMartin/readwise-mirror/releases/tag/1.1.1. Please let me know if you have any issues with the update. 

Here's an example of what the `Sync.md` file looks like in action
![image](https://user-images.githubusercontent.com/4033621/127798947-b1ae3e61-1cee-4c9b-9d31-c9644cad4f58.png)
