### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by piloteris** [jsonMartin/readwise-mirror#7]
Is there a way to get the location of a highlight when it imports

**Comment by jsonMartin** [comment]
Hey @piloteris, if the plugin detects any new changes in a book or article in Readwise, then it re-downloads the entire source (including all highlights) to ensure all content including tags and notes are up-to-date. 

Currently, it is only possible to see which book IDs were imported in the debug console (Ctrl+Shift+I on PC, Cmd+Shift+I on Mac); however, this information does not persist and will be lost after closing Obsidian.

My next release will have improved logging functionality and persist the Readwise updates into a log file; this should provide the info you're looking for. There is also already an issue created for this, pease follow the status here: https://github.com/jsonMartin/readwise-mirror/issues/6

**Comment by jsonMartin** [comment]
Hey @piloteris , sync log showing which books have new highlights have been added to newest Release v1.1.1: https://github.com/jsonMartin/readwise-mirror/releases/tag/1.1.1

Here's an example of what the `Sync.md` file looks like in action
![image](https://user-images.githubusercontent.com/4033621/127798947-b1ae3e61-1cee-4c9b-9d31-c9644cad4f58.png)
