### ISSUE TITLE
Google Play Books links point to Kindle app

### ISSUE THREAD

**Issue by natsharkman** [jsonMartin/readwise-mirror#8]
Thanks for this Obsidian plugin, I've just installed it but found it very useful so far.

One problem I've noticed: In highlights for books imported from [Google Play Books](https://help.readwise.io/article/117-how-do-i-import-highlights-from-google-play-books), there are embedded links that point to that location in the book on the GPB web interface, which is very handy for jumping into the book to see the context for that highlight. Once a GPB book is imported to Readwise, these links are correctly preserved in their web interface. However, when that book metadata and its highlights have been mirrored in Obsidian by this plugin, these GPB links for each highlight location appear as broken links to the Kindle app. Instead they should be preserved as-is and passed through to Obsidian.

Here's an example of one of the aforementioned links (login required): [Page 7](https://www.google.com/url?q=http://play.google.com/books/reader?printsec%3Dfrontcover%26output%3Dreader%26id%3DTM_AHwAAAEAJ%26source%3Dbooks-notes-export%26pg%3DGBS.PA7.w.0.0.0.1&sa=D&source=editors&ust=1614978754059000&usg=AOvVaw1It4OlJwJXpKzmuDTcVQw7)

Here's a file on Google Drive (for another book) that shows the links in the highlights file that gets imported to Readwise: [Why We Sleep](https://docs.google.com/document/d/1Isk0VZfG6lBeNAbcU4fvP00qHydQ43f8IdL5racg5gQ/edit?usp=sharing)

**Comment by jsonMartin** [comment]
Hi @natsharkman , thanks for reaching out with this issue. I haven't set up Google play books personally, but looked into the integration to see how it works.

I also investigated Readwise's API again, but unfortunately I couldn't find a method to check what source a book is coming from. The API only differentiates categories between: books, articles, tweets, supplementals or podcasts. 

The `source_url` field is just used for articles according to their documentation: "If source_type is not provided and source_url is, we assume it's an article. If source_url is not provided we assume book type."

Neither the `book` nor `highlight` fields in the API have the required data to determine whether the source is coming from Kindle, Apple Books, or Google Play Books. The default of Kindle link handling has been selected as that is the most common format. 

If Readwise adds this book source data to the API, then it will be fairly straightforward to add separate link handlers for Kindle / Google Play / etc.
